version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '11:00'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      prefix: fix
    ignore:
      - dependency-name: u-scripts
