version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      # Check for updates every weekday (Monday–Friday) @ 5am UTC.
      interval: daily
    # Always increase version requirement to match the new version.
    versioning-strategy: increase
    commit-message:
      # Use fix: to comply with conventional commits.
      prefix: fix
    ignore:
      # Avoid circular dependency updates
      - dependency-name: '@jr.codes/u'
