name: Close stale issues

on:
  schedule:
    # Run daily around midnight CST
    - cron: '0 6 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          days-before-stale: 60
          days-before-close: 15
          exempt-issue-labels: 'fresh'
          exempt-pr-labels: 'fresh,dependencies,security'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-label: 'stale'
          stale-issue-message: >
            🤖 This issue is stale because it hasn't had any recent activity.
            It'll be closed if no further activity occurs.
          stale-pr-label: 'stale'
          stale-pr-message: >
            🤖 This pull request is stale because it hasn't had any recent activity.
            It'll be closed if no further activity occurs.
